extend type MediaAsset {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "MediaAsset", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `MediaAsset`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "MediaAsset.user", purpose: IMPLICIT_REF_FIELD)
}
extend type PlatformPost {
  """
  ✨ Implicit foreign key field based on `PlatformPost`.`post`. It must match the value of `Post`.`id`. See `@ref` for how to customize it.
  """
  postId: UUID! @fdc_generated(from: "PlatformPost.post", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `PlatformPost`.`socialAccount`. It must match the value of `SocialAccount`.`id`. See `@ref` for how to customize it.
  """
  socialAccountId: UUID! @fdc_generated(from: "PlatformPost.socialAccount", purpose: IMPLICIT_REF_FIELD)
}
extend type Post {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Post", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Post`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Post.user", purpose: IMPLICIT_REF_FIELD)
}
extend type ProductService {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ProductService", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ProductService`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "ProductService.user", purpose: IMPLICIT_REF_FIELD)
}
extend type SocialAccount {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "SocialAccount", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `SocialAccount`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "SocialAccount.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Transaction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Transaction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`productService`. It must match the value of `ProductService`.`id`. See `@ref` for how to customize it.
  """
  productServiceId: UUID @fdc_generated(from: "Transaction.productService", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Transaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
